use std::{
    env, fs,
    path::{Path, PathBuf},
};

struct IconLibrarySource {
    const_name: &'static str,
    variant: &'static str,
    dir: &'static str,
    prefix: &'static str,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated_path = out_dir.join("generated_icons.rs");

    let sources = [
        IconLibrarySource {
            const_name: "LUCIDE_ICONS",
            variant: "Lucide",
            dir: "src/icons/assets/lucide",
            prefix: "lucide-",
        },
        IconLibrarySource {
            const_name: "HUGEICONS_ICONS",
            variant: "Hugeicons",
            dir: "src/icons/assets/hugeicons",
            prefix: "hugeicons-",
        },
    ];

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");
    generated.push_str("// Do not edit by hand.\n\n");

    for source in sources {
        write_library(&mut generated, &manifest_dir, source);
    }

    generated.push_str(
        r#"
pub(crate) fn generated_icons_for(library: IconLibrary) -> &'static [IconData] {
    match library {
        IconLibrary::Lucide => LUCIDE_ICONS,
        IconLibrary::Hugeicons => HUGEICONS_ICONS,
    }
}

pub(crate) fn generated_icon_lookup(
    library: IconLibrary,
    name: &str,
) -> Option<&'static IconData> {
    let icons = generated_icons_for(library);
    icons
        .binary_search_by(|icon| icon.name.cmp(name))
        .ok()
        .map(|index| &icons[index])
}
"#,
    );

    fs::write(generated_path, generated).unwrap();
}

fn write_library(generated: &mut String, manifest_dir: &Path, source: IconLibrarySource) {
    let dir = manifest_dir.join(source.dir);
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut icons = if dir.exists() {
        fs::read_dir(&dir)
            .unwrap()
            .filter_map(Result::ok)
            .filter_map(|entry| {
                let path = entry.path();
                if path.extension().and_then(|ext| ext.to_str()) != Some("svg") {
                    return None;
                }
                println!("cargo:rerun-if-changed={}", path.display());
                let file_name = path.file_name()?.to_str()?.to_owned();
                let name = file_name
                    .strip_suffix(".svg")
                    .unwrap_or(&file_name)
                    .strip_prefix(source.prefix)
                    .unwrap_or_else(|| file_name.strip_suffix(".svg").unwrap_or(&file_name))
                    .to_owned();
                Some((name, file_name))
            })
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };

    icons.sort_by(|a, b| a.0.cmp(&b.0));

    generated.push_str(&format!(
        "pub(crate) static {}: &[IconData] = &[\n",
        source.const_name
    ));

    for (name, file_name) in icons {
        let path = format!("/{}/{}", source.dir, file_name);
        generated.push_str(&format!(
            "    IconData {{ library: IconLibrary::{}, name: {:?}, svg: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?})) }},\n",
            source.variant, name, path
        ));
    }

    generated.push_str("];\n\n");
}
